# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Lida Shahmiri, PhD
description: "I am a doctoral researcher in Computer Science specialising in computer vision, machine learning, and statistical modelling. My work focuses on analysing large-scale visual datasets using Python and modern ML techniques to extract meaningful insights. I am particularly interested in developing scalable machine learning pipelines and applying AI methods to real-world problems. My research often involves interdisciplinary collaboration, combining AI theory with domain expertise in areas such as biological image analysis and pattern recognition. I have experience working with diverse research teams and communicating complex technical ideas through research presentations, outreach talks, and collaborative projects."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle:  <span style="color:#f58506"> Portfolio </span>
location: "Milton Keynes, UK"
resume_url: /docs/Lida_Shahmiri_CV.pdf 
avatar_image: /img/lida.jpeg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/lida-shahmiri/" # Add your linkedln handle
github: "https://github.com/LShahmiri/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

